// HS Code Chapters (01-99) with descriptions
export const HS_CHAPTERS = [
    { code: '01', name: 'Live animals' },
    { code: '02', name: 'Meat and edible meat offal' },
    { code: '03', name: 'Fish and crustaceans' },
    { code: '04', name: 'Dairy produce; eggs; honey' },
    { code: '05', name: 'Products of animal origin' },
    { code: '06', name: 'Live trees and plants' },
    { code: '07', name: 'Edible vegetables' },
    { code: '08', name: 'Edible fruit and nuts' },
    { code: '09', name: 'Coffee, tea, spices' },
    { code: '10', name: 'Cereals' },
    { code: '11', name: 'Milling products; malt; starches' },
    { code: '12', name: 'Oil seeds and oleaginous fruits' },
    { code: '13', name: 'Lac; gums, resins' },
    { code: '14', name: 'Vegetable plaiting materials' },
    { code: '15', name: 'Animal or vegetable fats and oils' },
    { code: '16', name: 'Preparations of meat, fish' },
    { code: '17', name: 'Sugars and sugar confectionery' },
    { code: '18', name: 'Cocoa and cocoa preparations' },
    { code: '19', name: 'Preparations of cereals, flour' },
    { code: '20', name: 'Preparations of vegetables, fruits' },
    { code: '21', name: 'Miscellaneous edible preparations' },
    { code: '22', name: 'Beverages, spirits and vinegar' },
    { code: '23', name: 'Residues from food industries' },
    { code: '24', name: 'Tobacco and manufactured tobacco' },
    { code: '25', name: 'Salt; sulphur; earths and stone' },
    { code: '26', name: 'Ores, slag and ash' },
    { code: '27', name: 'Mineral fuels, oils' },
    { code: '28', name: 'Inorganic chemicals' },
    { code: '29', name: 'Organic chemicals' },
    { code: '30', name: 'Pharmaceutical products' },
    { code: '31', name: 'Fertilizers' },
    { code: '32', name: 'Tanning or dyeing extracts' },
    { code: '33', name: 'Essential oils and cosmetics' },
    { code: '34', name: 'Soap, lubricants, waxes' },
    { code: '35', name: 'Albuminoidal substances' },
    { code: '36', name: 'Explosives; matches' },
    { code: '37', name: 'Photographic or cinematographic goods' },
    { code: '38', name: 'Miscellaneous chemical products' },
    { code: '39', name: 'Plastics and articles thereof' },
    { code: '40', name: 'Rubber and articles thereof' },
    { code: '41', name: 'Raw hides and skins' },
    { code: '42', name: 'Articles of leather' },
    { code: '43', name: 'Furskins and artificial fur' },
    { code: '44', name: 'Wood and articles of wood' },
    { code: '45', name: 'Cork and articles of cork' },
    { code: '46', name: 'Manufactures of straw' },
    { code: '47', name: 'Pulp of wood' },
    { code: '48', name: 'Paper and paperboard' },
    { code: '49', name: 'Printed books, newspapers' },
    { code: '50', name: 'Silk' },
    { code: '51', name: 'Wool, animal hair' },
    { code: '52', name: 'Cotton' },
    { code: '53', name: 'Other vegetable textile fibres' },
    { code: '54', name: 'Man-made filaments' },
    { code: '55', name: 'Man-made staple fibres' },
    { code: '56', name: 'Wadding, felt and nonwovens' },
    { code: '57', name: 'Carpets and textile floor coverings' },
    { code: '58', name: 'Special woven fabrics' },
    { code: '59', name: 'Impregnated textile fabrics' },
    { code: '60', name: 'Knitted or crocheted fabrics' },
    { code: '61', name: 'Knitted or crocheted apparel' },
    { code: '62', name: 'Woven apparel and accessories' },
    { code: '63', name: 'Other made up textile articles' },
    { code: '64', name: 'Footwear' },
    { code: '65', name: 'Headgear' },
    { code: '66', name: 'Umbrellas, walking-sticks' },
    { code: '67', name: 'Prepared feathers and down' },
    { code: '68', name: 'Articles of stone, plaster, cement' },
    { code: '69', name: 'Ceramic products' },
    { code: '70', name: 'Glass and glassware' },
    { code: '71', name: 'Pearls, precious stones, metals' },
    { code: '72', name: 'Iron and steel' },
    { code: '73', name: 'Articles of iron or steel' },
    { code: '74', name: 'Copper and articles thereof' },
    { code: '75', name: 'Nickel and articles thereof' },
    { code: '76', name: 'Aluminium and articles thereof' },
    { code: '77', name: 'Reserved for future use' },
    { code: '78', name: 'Lead and articles thereof' },
    { code: '79', name: 'Zinc and articles thereof' },
    { code: '80', name: 'Tin and articles thereof' },
    { code: '81', name: 'Other base metals' },
    { code: '82', name: 'Tools, cutlery of base metal' },
    { code: '83', name: 'Miscellaneous articles of base metal' },
    { code: '84', name: 'Machinery and mechanical appliances' },
    { code: '85', name: 'Electrical machinery and equipment' },
    { code: '86', name: 'Railway or tramway locomotives' },
    { code: '87', name: 'Vehicles other than railway' },
    { code: '88', name: 'Aircraft, spacecraft' },
    { code: '89', name: 'Ships, boats' },
    { code: '90', name: 'Optical, photographic instruments' },
    { code: '91', name: 'Clocks and watches' },
    { code: '92', name: 'Musical instruments' },
    { code: '93', name: 'Arms and ammunition' },
    { code: '94', name: 'Furniture; bedding, lamps' },
    { code: '95', name: 'Toys, games and sports equipment' },
    { code: '96', name: 'Miscellaneous manufactured articles' },
    { code: '97', name: 'Works of art, antiques' },
    { code: '98', name: 'Special classification provisions' },
    { code: '99', name: 'Special import/export provisions' },
];
